create table if not exists public.food_sides (
  id bigint generated by default as identity primary key,
  food_id bigint references public.foods(id) on delete cascade not null,
  side_id bigint references public.sides(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(food_id, side_id)
);

-- Add RLS policies if needed (assuming public/authenticated access for now similar to others)
alter table public.food_sides enable row level security;

create policy "Public read access"
  on public.food_sides for select
  using ( true );

create policy "Authenticated insert access"
  on public.food_sides for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated delete access"
  on public.food_sides for delete
  using ( auth.role() = 'authenticated' );
